package viewtools

import (
	"syscall/js"

	"github.com/josephbudd/kickwasm/examples/colors/renderer/notjs"
)

/*

WARNING:

DO NOT EDIT THIS FILE.

*/

// Visibility class names.
const (
	spawnIDReplacePattern  = "{{.SpawnID}}"
	TabClassName           = "tab"
	SelectedTabClassName   = "selected-tab"
	UnSelectedTabClassName = "unselected-tab"
	TabPanelClassName      = "panel-bound-to-tab"

	TabBarClassName      = "tab-bar"
	UnderTabBarClassName = "under-tab-bar"

	PanelClassName                   = "panel"
	PanelWithHeadingClassName        = "panel-with-heading"
	PanelWithTabBarClassName         = "panel-with-tab-bar"
	PanelHeadingClassName            = "heading-of-panel"
	PanelHeadingLevelPrefixClassName = "heading-of-panel-level-"
	TabPanelGroupClassName           = "inner-panel"
	UserContentClassName             = "user-content"
	ResizeMeWidthClassName           = "resize-me-width"

	SliderClassName                  = "slider"
	SliderPanelClassName             = "slider-panel"
	SliderPanelInnerClassName        = "slider-panel-pad"
	SliderPanelInnerSiblingClassName = "slider-panel-inner-sibling"
	SliderButtonPadClassName         = "slider-button-pad"

	SeenClassName       = "seen"
	UnSeenClassName     = "unseen"
	ToBeSeenClassName   = "tobe-seen"
	ToBeUnSeenClassName = "tobe-unseen"

	CookieCrumbClassName            = "cookie-crumb"
	CookieCrumbLevelPrefixClassName = "cookie-crumb-level-"

	VScrollClassName =  "vscroll"
	HVScrollClassName = "hvscroll"	

	MasterID           = "tabsMasterView"
	HomeID             = "tabsMasterView-home"
	HomePadID          = "tabsMasterView-home-pad"
	SliderID           = "tabsMasterView-home-slider"
	SliderBackID       = "tabsMasterView-home-slider-back"
	SliderCollectionID = "tabsMasterView-home-slider-collection"

	BackIDAttribute         = "backid"
	BackColorLevelAttribute = "backColorLevel"
)

// Tools are application view tools.
type Tools struct {
	body                               js.Value
	tabsMasterview                     js.Value
	tabsMasterviewHome                 js.Value
	tabsMasterviewHomeButtonPad        js.Value
	tabsMasterviewHomeSlider           js.Value
	tabsMasterviewHomeSliderBack       js.Value
	tabsMasterviewHomeSliderCollection js.Value

	Document js.Value
	Global   js.Value

	// closer
	closerMasterView js.Value
	lastMasterView   js.Value
	// modal
	modalMasterView        js.Value
	modalMasterViewCenter  js.Value
	modalMasterViewH1      js.Value
	modalMasterViewMessage js.Value
	modalMasterViewClose   js.Value
	modalQueue             []*modalViewData
	modalQueueLastIndex    int
	beingModal             bool
	modalCallBack          func()
	// misc
	alert   js.Value
	console js.Value
	// groups
	buttonPanelsMap map[string][]js.Value
	// slider
	here      js.Value
	backStack []js.Value
	// tabber
	tabberLastPanelID     string
	tabberTabBarLastPanel map[string]string
	// button locking
	buttonsLocked             bool
	buttonsLockedMessageTitle string
	buttonsLockedMessageText  string

	// call backs
	jsCallBacks map[uint64][]js.Func

	NotJS *notjs.NotJS

	// spawns

	spawnID               uint64
	SpawnIDReplacePattern string

	// user content

	panelNameHVScroll map[string]bool
}

// NewTools constructs a new Tools
func NewTools(notJS *notjs.NotJS) *Tools {
	g := js.Global()
	v := &Tools{
		Document:              g.Get("document"),
		Global:                g,
		NotJS:                 notJS,
		SpawnIDReplacePattern: spawnIDReplacePattern,

		buttonPanelsMap: make(map[string][]js.Value, 100),
		here:            js.Undefined(),
		alert:           g.Get("alert"),
		console:         g.Get("console"),
		jsCallBacks:     make(map[uint64][]js.Func, 100),

		panelNameHVScroll: map[string]bool{"Service1Level1ButtonPanel":false, "Service1Level1MarkupPanel":false, "Service1Level2ButtonPanel":false, "Service1Level2MarkupPanel":false, "Service1Level3ButtonPanel":false, "Service1Level3MarkupPanel":false, "Service1Level4ButtonPanel":false, "Service1Level4MarkupPanel":false, "Service1Level5ButtonPanel":false, "Service1Level5MarkupPanel":false, "Service2Level1ButtonPanel":false, "Service2Level1MarkupPanel":false, "Service2Level2ButtonPanel":false, "Service2Level2MarkupPanel":false, "Service2Level3ButtonPanel":false, "Service2Level3MarkupPanel":false, "Service2Level4ButtonPanel":false, "Service2Level4MarkupPanel":false, "Service2Level5ButtonPanel":false, "Service2Level5MarkupPanel":false, "Service3Level1ButtonPanel":false, "Service3Level1MarkupPanel":false, "Service3Level2ButtonPanel":false, "Service3Level2MarkupPanel":false, "Service3Level3ButtonPanel":false, "Service3Level3MarkupPanel":false, "Service3Level4ButtonPanel":false, "Service3Level4MarkupPanel":false, "Service3Level5ButtonPanel":false, "Service3Level5MarkupPanel":false, "Service4Level1ButtonPanel":false, "Service4Level1MarkupPanel":false, "Service4Level2ButtonPanel":false, "Service4Level2MarkupPanel":false, "Service4Level3ButtonPanel":false, "Service4Level3MarkupPanel":false, "Service4Level4ButtonPanel":false, "Service4Level4MarkupPanel":false, "Service4Level5ButtonPanel":false, "Service4Level5MarkupPanel":false, "Service5Level1ButtonPanel":false, "Service5Level1MarkupPanel":false, "Service5Level2ButtonPanel":false, "Service5Level2MarkupPanel":false, "Service5Level3ButtonPanel":false, "Service5Level3MarkupPanel":false, "Service5Level4ButtonPanel":false, "Service5Level4MarkupPanel":false, "Service5Level5ButtonPanel":false, "Service5Level5MarkupPanel":false},
	}
	bodies := notJS.GetElementsByTagName("body")
	v.body = bodies[0]
	v.tabsMasterview = notJS.GetElementByID(MasterID)
	v.tabsMasterviewHome = notJS.GetElementByID(HomeID)
	v.tabsMasterviewHomeButtonPad = notJS.GetElementByID(HomePadID)
	v.tabsMasterviewHomeSlider = notJS.GetElementByID(SliderID)
	v.tabsMasterviewHomeSliderBack = notJS.GetElementByID(SliderBackID)
	v.tabsMasterviewHomeSliderCollection = notJS.GetElementByID(SliderCollectionID)
	// closer
	v.closerMasterView = notJS.GetElementByID("closerMasterView")
	// modal
	v.modalMasterView = notJS.GetElementByID("modalInformationMasterView")
	v.modalMasterViewCenter = notJS.GetElementByID("modalInformationMasterView-center")
	v.modalMasterViewH1 = notJS.GetElementByID("modalInformationMasterView-h1")
	v.modalMasterViewMessage = notJS.GetElementByID("modalInformationMasterView-message")
	v.modalMasterViewClose = notJS.GetElementByID("modalInformationMasterView-close")
	v.modalQueue = make([]*modalViewData, 5, 5)
	v.modalQueueLastIndex = -1
	cb := v.RegisterEventCallBack(v.handleModalMasterViewClose, true, true, true)
	notJS.SetOnClick(v.modalMasterViewClose, cb)

	// misc
	v.initializeGroups()
	v.initializeSlider()
	v.initializeResize()
	v.initializeCloser()
	v.initializeTabBar()

	return v
}
