// +build js, wasm

package schoolcoursekeytestpanel

import (
	"fmt"
	"syscall/js"

	"github.com/josephbudd/kickwasm/proofs/tp2b/tp2btest/rendererprocess/api/markup"
	"github.com/josephbudd/kickwasm/proofs/tp2b/tp2btest/rendererprocess/framework/viewtools"
)

/*

	DO NOT EDIT THIS FILE.

	This file is generated by kickasm and regenerated by rekickasm.

*/

// panelGroup is a group of 4 panels.
// It also has show panel funcs for each panel in this panel group.
type panelGroup struct {
	schoolCourseKeyCompletedPanel js.Value
	schoolCourseKeyChoosePanel js.Value
	schoolCourseKeyPracticePanel js.Value
	schoolCourseKeyTestPanel js.Value
}

func (group *panelGroup) defineMembers() (err error) {

	defer func() {
		if err != nil {
			err = fmt.Errorf("(group *panelGroup) defineMembers(): %w", err)
		}
	}()

    var panel *markup.Element
 if panel = document.ElementByID("mainMasterView_home_pad_SchoolButton_SchoolPanel_tab_bar-SchoolCourseKeyTabPanel-inner-SchoolCourseKeyCompletedPanel"); panel == nil {
	err = fmt.Errorf("unable to find #mainMasterView_home_pad_SchoolButton_SchoolPanel_tab_bar-SchoolCourseKeyTabPanel-inner-SchoolCourseKeyCompletedPanel")
		return
    }
    group.schoolCourseKeyCompletedPanel = panel.JSValue()
 if panel = document.ElementByID("mainMasterView_home_pad_SchoolButton_SchoolPanel_tab_bar-SchoolCourseKeyTabPanel-inner-SchoolCourseKeyChoosePanel"); panel == nil {
	err = fmt.Errorf("unable to find #mainMasterView_home_pad_SchoolButton_SchoolPanel_tab_bar-SchoolCourseKeyTabPanel-inner-SchoolCourseKeyChoosePanel")
		return
    }
    group.schoolCourseKeyChoosePanel = panel.JSValue()
 if panel = document.ElementByID("mainMasterView_home_pad_SchoolButton_SchoolPanel_tab_bar-SchoolCourseKeyTabPanel-inner-SchoolCourseKeyPracticePanel"); panel == nil {
	err = fmt.Errorf("unable to find #mainMasterView_home_pad_SchoolButton_SchoolPanel_tab_bar-SchoolCourseKeyTabPanel-inner-SchoolCourseKeyPracticePanel")
		return
    }
    group.schoolCourseKeyPracticePanel = panel.JSValue()
 if panel = document.ElementByID("mainMasterView_home_pad_SchoolButton_SchoolPanel_tab_bar-SchoolCourseKeyTabPanel-inner-SchoolCourseKeyTestPanel"); panel == nil {
	err = fmt.Errorf("unable to find #mainMasterView_home_pad_SchoolButton_SchoolPanel_tab_bar-SchoolCourseKeyTabPanel-inner-SchoolCourseKeyTestPanel")
		return
    }
    group.schoolCourseKeyTestPanel = panel.JSValue()

	return
}

/*
	Show panel funcs.

	Call these from the controller, presenter and messenger.
*/

// showSchoolCourseKeyCompletedPanel shows the panel you named SchoolCourseKeyCompletedPanel while hiding any other panels in this panel group.
// That panel will become visible only when this group of panels becomes visible.
/* Your note for that panel is:
Displayed when the user has successfully copied for this lesson.
Maybe it should display the results.

*/
func (group *panelGroup) showSchoolCourseKeyCompletedPanel() {
	viewtools.ShowPanelInTabGroup(group.schoolCourseKeyCompletedPanel)
}


// showSchoolCourseKeyChoosePanel shows the panel you named SchoolCourseKeyChoosePanel while hiding any other panels in this panel group.
// That panel will become visible only when this group of panels becomes visible.
/* Your note for that panel is:
Displayed when the user has successfully copied for this lesson.
Maybe it should display the results.

*/
func (group *panelGroup) showSchoolCourseKeyChoosePanel() {
	viewtools.ShowPanelInTabGroup(group.schoolCourseKeyChoosePanel)
}


// showSchoolCourseKeyPracticePanel shows the panel you named SchoolCourseKeyPracticePanel while hiding any other panels in this panel group.
// That panel will become visible only when this group of panels becomes visible.
/* Your note for that panel is:
A page to let the user copy without recording the results.
*/
func (group *panelGroup) showSchoolCourseKeyPracticePanel() {
	viewtools.ShowPanelInTabGroup(group.schoolCourseKeyPracticePanel)
}


// showSchoolCourseKeyTestPanel shows the panel you named SchoolCourseKeyTestPanel while hiding any other panels in this panel group.
// This panel will become visible only when this group of panels becomes visible.
/* Your note for this panel is:
A page to let the user copy with results recorded.
*/
func (group *panelGroup) showSchoolCourseKeyTestPanel() {
	viewtools.ShowPanelInTabGroup(group.schoolCourseKeyTestPanel)
}

