title : DeepTest
importPath : github.com/josephbudd/kickwasm/examples/deepTest
buttons :
  - name : b1
    label : Button 1
    heading : Button 1 Heading.
    panelFiles :
      - home1/panel1.yaml
      - home1/panel2.yaml
  - name : b2
    label : Button 2
    heading : Button 2 Heading.
    panelFiles :
      - home2/panel3.yaml
      - home2/panel4.yaml

