// +build js, wasm

package tabsbuttontabbarpanel

import (
	"github.com/josephbudd/kickwasm/examples/spawntabs/rendererprocess/lpc"
	"github.com/josephbudd/kickwasm/examples/spawntabs/rendererprocess/notjs"
	"github.com/josephbudd/kickwasm/examples/spawntabs/rendererprocess/paneling"
	"github.com/josephbudd/kickwasm/examples/spawntabs/rendererprocess/spawnPanels/TabsButton/TabsButtonTabBarPanel/SecondTab"
	"github.com/josephbudd/kickwasm/examples/spawntabs/rendererprocess/viewtools"
)

/*

	DO NOT EDIT THIS FILE.

	This file is generated by kickasm and regenerated by rekickasm.

*/

const (
	tabBarID = "tabsMasterView_home_pad_TabsButton_TabsButtonTabBarPanel_tab_bar"
)

// Prepare prepares the tab bar and it's panels and templates to be spawned.
// This is called once by package main when the application starts.
func Prepare(quitChan, eojChan chan struct{}, receiveChan lpc.Receiving, sendChan lpc.Sending,
	vtools *viewtools.Tools, njs *notjs.NotJS, help *paneling.Help) {

	secondtab.Prepare(quitChan, eojChan, receiveChan, sendChan, vtools, njs, help)
}
