// +build js, wasm

package secondtab

import (
	"github.com/josephbudd/kickwasm/examples/spawnwidgets/rendererprocess/framework/lpc"
	"github.com/josephbudd/kickwasm/examples/spawnwidgets/rendererprocess/paneling"
	helloworldtemplatepanel "github.com/josephbudd/kickwasm/examples/spawnwidgets/rendererprocess/spawnPanels/TabsButton/TabsButtonTabBarPanel/SecondTab/HelloWorldTemplatePanel"
)

/*

	DO NOT EDIT THIS FILE.

	This file is generated by kickasm and regenerated by rekickasm.

*/

// Prepare initializes this package in preparation for spawning.
func Prepare(quitChan, eojChan chan struct{}, receiveChan lpc.Receiving, sendChan lpc.Sending, help *paneling.Help) {

	helloworldtemplatepanel.Prepare(quitChan, eojChan, receiveChan, sendChan, help)
}
