// +build js, wasm

package main

import (
	"github.com/pkg/errors"

	"github.com/josephbudd/kickwasm/examples/spawntabs/rendererprocess/lpc"
	"github.com/josephbudd/kickwasm/examples/spawntabs/rendererprocess/notjs"
	"github.com/josephbudd/kickwasm/examples/spawntabs/rendererprocess/paneling"
	createpanel "github.com/josephbudd/kickwasm/examples/spawntabs/rendererprocess/panels/TabsButton/TabsButtonTabBarPanel/FirstTab/CreatePanel"
	tabsbuttontabbarpanel "github.com/josephbudd/kickwasm/examples/spawntabs/rendererprocess/spawnPanels/TabsButton/TabsButtonTabBarPanel"
	"github.com/josephbudd/kickwasm/examples/spawntabs/rendererprocess/viewtools"
)

/*

	DO NOT EDIT THIS FILE.

	This file is generated by kickasm and regenerated by rekickasm.

*/

func doPanels(quitChan, eojChan chan struct{}, receiveChan lpc.Receiving, sendChan lpc.Sending,
	tools *viewtools.Tools, notJS *notjs.NotJS, help *paneling.Help) (err error) {
	
	defer func() {
		if err != nil {
			err = errors.WithMessage(err, "doPanels")
			tools.ConsoleLog("Error: " + err.Error())
		}
	}()

	// 1. Prepare the spawn panels.
	tabsbuttontabbarpanel.Prepare(quitChan, eojChan, receiveChan, sendChan, tools, notJS, help)

	// 2. Construct the panel code.
	var createPanel *createpanel.Panel
	if createPanel, err = createpanel.NewPanel(quitChan, eojChan, receiveChan, sendChan, tools, notJS, help); err != nil {
		return
	}

	// 3. Size the app.
	tools.SizeApp()

	// 4. Start each panel's message and event dispatchers.
	createPanel.StartDispatchers()

	// 5. Start each panel's initial calls.
	createPanel.InitialJobs()

	return
}
