// +build js, wasm

package tabsbuttontabbarpanel

import (
	"context"

	"github.com/josephbudd/kickwasm/examples/spawnwidgets/rendererprocess/framework/lpc"
	"github.com/josephbudd/kickwasm/examples/spawnwidgets/rendererprocess/paneling"
	"github.com/josephbudd/kickwasm/examples/spawnwidgets/rendererprocess/spawnPanels/TabsButton/TabsButtonTabBarPanel/SecondTab"
)

/*

	DO NOT EDIT THIS FILE.

	This file is generated by kickasm and regenerated by rekickasm.

*/

const (
	tabBarID = "mainMasterView_home_pad_TabsButton_TabsButtonTabBarPanel_tab_bar"
)

// Prepare prepares the tab bar and it's panels and templates to be spawned.
// This is called once by package main when the application starts.
func Prepare(ctx context.Context, ctxCancel context.CancelFunc, receiveChan lpc.Receiving, sendChan lpc.Sending, help *paneling.Help) {

	secondtab.Prepare(ctx, ctxCancel, receiveChan, sendChan, help)
}
