package main

import (
	"github.com/josephbudd/kickwasm/examples/colors/domain/store"
)

/*
	DO NOT EDIT THIS FILE.

	USE THE TOOL kickstore TO ADD OR REMOVE STORES.

	kickstore WILL EDIT THIS FILE FOR YOU.
*/

// buildStores makes the bolt data stores.
// However, you haven't added any stores yet.
func buildStores() (stores *store.Stores, err error) {
	stores = &store.Stores{}
	return
}
