title : Test 1
importPath : github.com/josephbudd/kickwasm/examples/test1
stores :
  - Test1
services :
  - name : Service1
    button :
      label : Button 1
      name : OneButton
      heading : Button 1 Heading.
      panelFiles :
        - service1/panel1.yaml
        - service1/panel2.yaml
  - name : Service2
    button :
      label : Button 2
      name : TwoButton
      heading : Button 2 Heading.
      panelFiles :
        - service2/panel3.yaml
        - service2/panel5.yaml

