// +build js, wasm

package action1level1markuppanel

import (
	"fmt"
	"syscall/js"

	"github.com/josephbudd/kickwasm/examples/colors/rendererprocess/api/markup"
	"github.com/josephbudd/kickwasm/examples/colors/rendererprocess/framework/viewtools"
)

/*

	DO NOT EDIT THIS FILE.

	This file is generated by kickasm and regenerated by rekickasm.

*/

// panelGroup is a group of 1 panel.
// It also has a show panel func for each panel in this panel group.
type panelGroup struct {
	action1Level1MarkupPanel js.Value
}

func (group *panelGroup) defineMembers() (err error) {

	defer func() {
		if err != nil {
			err = fmt.Errorf("(group *panelGroup) defineMembers(): %w", err)
		}
	}()

    var panel *markup.Element
 if panel = document.ElementByID("mainMasterView-home-pad-Action1Button-Action1Level1ButtonPanel-Action1Level1ContentButton-Action1Level1MarkupPanel"); panel == nil {
	err = fmt.Errorf("unable to find #mainMasterView-home-pad-Action1Button-Action1Level1ButtonPanel-Action1Level1ContentButton-Action1Level1MarkupPanel")
		return
    }
    group.action1Level1MarkupPanel = panel.JSValue()

	return
}

/*
	Show panel funcs.

	Call these from the controller, presenter and messenger.
*/

// showAction1Level1MarkupPanel shows the panel you named Action1Level1MarkupPanel while hiding any other panels in this panel group.
// This panel's id is mainMasterView-home-pad-Action1Button-Action1Level1ButtonPanel-Action1Level1ContentButton-Action1Level1MarkupPanel.
// This panel either becomes visible immediately or whenever this group of panels is made visible.  Whenever could be immediately if this panel group is currently visible.
// Param force boolean effects when this panel becomes visible.
//  * if force is true then
//    immediately if the home button pad is not currently displayed;
//    whenever if the home button pad is currently displayed.
//  * if force is false then whenever.
/* Your note for this panel is:
This is the only content.
Brought to you in the first service color.

*/
func (group *panelGroup) showAction1Level1MarkupPanel(force bool) {
	viewtools.ShowPanelInButtonGroup(group.action1Level1MarkupPanel, force)
}
