package templates

// FrameworkDoPanelsGo is rendererprocess/framework/panels.go.
const FrameworkDoPanelsGo = `{{$Dot := .}}// +build js, wasm

package framework

import (
	"context"
	"fmt"
	"log"

{{ range .Imports }}
	{{.}}{{end}}
)

/*

	DO NOT EDIT THIS FILE.

	This file is generated by kickasm and regenerated by rekickasm.

*/

// DoMarkupPanels builds and runs the markup panels.
func DoMarkupPanels(ctx context.Context, ctxCancel context.CancelFunc, receiveChan lpc.Receiving, sendChan lpc.Sending, help *paneling.Help) (err error) {
	
	defer func() {
		if err != nil {
			err = fmt.Errorf("DoMarkupPanels: %w", err)
			log.Println("Error: " + err.Error())
		}
	}()

	// 1. Prepare the spawn panels.{{ range $packageName, $path := .SpawnTabBarNamePath}}
	{{call $Dot.PackageNameCase $packageName}}.Prepare(ctx, ctxCancel, receiveChan, sendChan, help){{end}}

	// 2. Construct the panel code.{{range $name, $path := .PanelNamePath}}
	var {{call $Dot.LowerCamelCase $name}} *{{call $Dot.PackageNameCase $name}}.Panel
	if {{call $Dot.LowerCamelCase $name}}, err = {{call $Dot.PackageNameCase $name}}.NewPanel(ctx, ctxCancel, receiveChan, sendChan, help); err != nil {
		return
	}{{end}}

	// 3. Size the app.
	viewtools.SizeApp()

	// 4. Start each panel's message and event dispatchers.{{range $name, $path := .PanelNamePath}}
	{{call $Dot.LowerCamelCase $name}}.StartDispatchers(){{end}}

	// 5. Start each panel's initial calls.{{range $name, $path := .PanelNamePath}}
	{{call $Dot.LowerCamelCase $name}}.InitialJobs(){{end}}

	return
}
`
