package templates

// SpawnTabPrepare is the tab's prepare.go template.
const SpawnTabPrepare = `{{$Dot := .}}// +build js, wasm

package {{call .PackageNameCase .TabName}}

import (
	"context"
{{ range .PrepareImports }}
	{{.}}{{end}}
)

/*

	DO NOT EDIT THIS FILE.

	This file is generated by kickasm and regenerated by rekickasm.

*/

// Prepare initializes this package in preparation for spawning.
func Prepare(ctx context.Context, ctxCancel context.CancelFunc, receiveChan lpc.Receiving, sendChan lpc.Sending, help *paneling.Help) {
	rendererProcessCtx = ctx
{{ range .PanelNames }}
	{{ call $Dot.PackageNameCase . }}.Prepare(ctxCancel, receiveChan, sendChan, help){{end}}
}
`

// SpawnTabSpawn is the tab's spawn.go template.
const SpawnTabSpawn = `{{$Dot := .}}// +build js, wasm

package {{call .PackageNameCase .TabName}}

import (
	"context"
	"fmt"
	"strings"
	"syscall/js"

{{ range .SpawnImports }}
	{{.}}{{end}}
)

/*

	DO NOT EDIT THIS FILE.

	This file is generated by kickasm and regenerated by rekickasm.

*/

const (
	tabBarID = "{{.TabBarID}}"
	tabName  = "{{.TabName}}"
)

var (
	markupTemplatePaths = {{.MarkupTemplatePaths}}
	rendererProcessCtx  context.Context
)

// Tab represents a tab that will spawn and unspawn an html tab bar tab.
type Tab struct {
	ctx        context.Context
	ctxCancel  context.CancelFunc
	uniqueID   uint64
	hTMLButton js.Value
}

// Spawn creates the DOM elements and go code for a tab.
// This is called by the tab bar.
// Param tabLabel is the label in the tab button. The button's innerText.
// Param panelHeading is the heading for each panel.
// Param panelData is an empty interface passed to each panel's spawn func.
// Returns the tab's context cancel func ( which is the tab's unspawn func ) and the error.
func Spawn(tabLabel, panelHeading string, panelData interface{}) (tabCtxCancel context.CancelFunc, err error) {

	defer func() {
		if err != nil {
			err = fmt.Errorf("{{call .PackageNameCase .TabName}}.Spawn(): %w", err)
		}
	}()

	// Spawn the DOM elements.
	var jsTabButton js.Value
	var jsTabPanelHeader js.Value
	var uniqueID uint64
	var panelNameID map[string]string
	if jsTabButton, jsTabPanelHeader, uniqueID, panelNameID, err = viewtools.SpawnTab(tabBarID, tabName, tabLabel, panelHeading, markupTemplatePaths); err != nil {
		return
	}
	tabButton := markup.NewElement(jsTabButton, uniqueID)
	tabPanelHeader := markup.NewElement(jsTabPanelHeader, uniqueID)
	// Define the tab.
	tabCtx, tabCtxCancel := context.WithCancel(rendererProcessCtx)
	tab := &Tab{
		ctx:        tabCtx,
		ctxCancel:  tabCtxCancel,
		hTMLButton: jsTabButton,
		uniqueID:   uniqueID,
	}
	// Build the go code.
{{ range .PanelNames }}
	if err = {{ call $Dot.PackageNameCase . }}.BuildPanel(tabCtx, tabCtxCancel, uniqueID, tabButton, tabPanelHeader, panelNameID, panelData); err != nil {
		return
	}{{end}}
	viewtools.IncSpawnedPanels({{len .PanelNames}})

	go func(t *Tab) {
		select {
		case <-t.ctx.Done():
			t.unSpawn()
		}
	}(tab)

	return
}

// unSpawn totally removes the DOM elements and go code of a spawned tab.
// Returns the error.
func (tab *Tab) unSpawn() (err error) {

	defer func() {
		if err != nil {
			err = fmt.Errorf("{{call .PackageNameCase .TabName}}.unSpawn(): uniqueID is %d: %w", tab.uniqueID, err)
		}
	}()

	viewtools.DecSpawnedPanels({{len .PanelNames}})

	messages := make([]string, 0, 2)
	// Remove the tab and panels from the DOM.
	if err = viewtools.UnSpawnTab(tab.hTMLButton); err != nil {
		messages = append(messages, err.Error())
	}
	// Unregister each panel controller's javascript call backs.
	if err = callback.UnRegisterCallBacks(tab.uniqueID); err != nil {
		messages = append(messages, err.Error())
	}
	// construct a new error from the accumulated errors.
	if len(messages) > 0 {
		err = fmt.Errorf(strings.Join(messages, "\n"))
	}
	return
}

func (tab *Tab) Tab() js.Value {
	return tab.hTMLButton
}

func (tab *Tab) UniqueID() uint64 {
	return tab.uniqueID
}
`
