package templates

// SpawnTabPanelAPI is the genereric renderer spawn data.go template.
const SpawnTabPanelAPI = `{{$Dot := .}}// +build js, wasm

package {{call .PackageNameCase .PanelName}}

import (
	"fmt"

	"github.com/pkg/errors"

	"{{.ApplicationGitPath}}{{.ImportRendererLPC}}"
	"{{.ApplicationGitPath}}{{.ImportRendererMarkup}}"
	"{{.ApplicationGitPath}}{{.ImportRendererPaneling}}"
)

/*

	Panel name: {{.PanelName}}

*/

/*

	DO NOT EDIT THIS FILE.

*/

// Prepare prepares the panel to be spawned.
// This is called once by package main when the application starts.
func Prepare(quitChan, eojChan chan struct{}, receiveChan lpc.Receiving, sendChan lpc.Sending, phelp *paneling.Help) {
	quitCh = quitChan
	eojCh = eojChan
	receiveCh = receiveChan
	sendCh = sendChan
	help = phelp
}

// BuildPanel builds the panel's go code.
// Returns the error.
func BuildPanel(uniqueID uint64, tabButton, tabPanelHeader *markup.Element, panelNameID map[string]string, panelData interface{}, unspawn func() error) (prepareToUnSpawn func(), err error) {

	defer func() {
		if err != nil {
			message := fmt.Sprintf("%s.BuildPanel()", "{{call .PackageNameCase .PanelName}}")
			err = errors.WithMessage(err, message)
		}
	}()

	// make the panel
	panel := newPanel(uniqueID, tabButton, tabPanelHeader, panelNameID, panelData, unspawn)
	prepareToUnSpawn = panel.PrepareToUnSpawn

	if err = panel.group.defineMembers(); err != nil {
		return
	}
	if err = panel.controller.defineControlsHandlers(); err != nil {
		return
	}
	if err = panel.presenter.defineMembers(); err != nil {
		return
	}
	panel.messenger.dispatchMessages()
	panel.controller.initialCalls()
	panel.messenger.initialSends()

	return
}

// PrepareToUnSpawn prepares to unspawn.
func (panel *spawnedPanel) PrepareToUnSpawn() {
	panel.messenger.unSpawningCh <- struct{}{}
	panel.controller.UnSpawning()
}
`
