package templates

// SpawnTabPanelGroup is the genereric renderer spawns group template.
const SpawnTabPanelGroup = `{{$Dot := .}}{{$lpg := len .PanelGroup}}package {{call .PackageNameCase .PanelName}}

import (
	"syscall/js"

	"github.com/pkg/errors"
)

/*

	DO NOT EDIT THIS FILE.

	This file is generated by kickasm and regenerated by rekickasm.

*/

const (
	tabBarID        = "{{.TabBarID}}"
	tabName         = "{{.TabName}}"
	tabPanelHeading = "{{.PanelHeading}}"
)

// panelGroup is a group of {{$lpg}} panel{{if gt $lpg 1}}s{{end}}.
// It also has {{if eq $lpg 1}}a {{end}}show panel func{{if gt $lpg 1}}s{{end}} for each panel in this panel group.
type panelGroup struct {
	uniqueID uint64
	panelNameID map[string]string
{{range $panel := .PanelGroup}}
	{{call $Dot.LowerCamelCase $panel.Name}} js.Value{{end}}
}

func (group *panelGroup) defineMembers() (err error) {

	defer func() {
		if err != nil {
			err = errors.WithMessage(err, "(group *panelGroup) defineMembers()")
		}
	}()

	var id string
{{range $panel := .PanelGroup}}	id = tools.BuildSpawnTabButtonMarkupPanelID(tabBarID, tabName, "{{$panel.Name}}", group.uniqueID)
	if group.{{call $Dot.LowerCamelCase $panel.Name}} = notJS.GetElementByID(id); group.{{call $Dot.LowerCamelCase $panel.Name}} == null {
		err = errors.New("unable to find #" + id)
		return
	}
{{end}}
	return
}

/*
	Show panel funcs.

	Call these from the controler, presenter and caller.
*/{{range $panel := .PanelGroup}}

// show{{$panel.Name}} shows the panel you named {{$panel.Name}} while hiding any other panels in this panel group.
// {{if eq $Dot.PanelName $panel.Name}}This{{else}}That{{end}} panel will become visible only when this group of panels becomes visible.
/* Your note for {{if eq $Dot.PanelName $panel.Name}}this{{else}}that{{end}} panel is:
{{$panel.Note}}
*/
func (group *panelGroup) show{{$panel.Name}}() {
	tools.ShowPanelInTabGroup(group.{{call $Dot.LowerCamelCase $panel.Name}})
}
{{end}}
`
