package templates

// SpawnTabBarPrepare is the genereric renderer spawn tab bar prepare.go template.
const SpawnTabBarPrepare = `{{$Dot := .}}// +build js, wasm

package {{call .PackageNameCase .TabBarName}}

import (
	"context"

{{ range .Imports }}	"{{$Dot.ApplicationGitPath}}{{.}}"
{{end}})

/*

	DO NOT EDIT THIS FILE.

	This file is generated by kickasm and regenerated by rekickasm.

*/

const (
	tabBarID = "{{.TabBarID}}"
)

// Prepare prepares the tab bar and it's panels and templates to be spawned.
// This is called once by package main when the application starts.
func Prepare(ctx context.Context, ctxCancel context.CancelFunc, receiveChan lpc.Receiving, sendChan lpc.Sending, help *paneling.Help) {
{{ range .TabNames }}
	{{ call $Dot.PackageNameCase . }}.Prepare(ctx, ctxCancel, receiveChan, sendChan, help){{end}}
}
`
