package templates

// ViewToolsTabBar is the renderer/viewtools/tabbar.go template.
const ViewToolsTabBar = `package viewtools

import (
	"strings"
	"syscall/js"
)

/*
	WARNING:

	DO NOT EDIT THIS FILE.

*/

// ForceTabButtonClick implements the behavior of a tab button being clicked by the user.
func (tools *Tools) ForceTabButtonClick(button js.Value) {
	tools.handleTabButtonOnClick(button)
}

func (tools *Tools) initializeTabBar() {
	notJS := tools.notJS
	tools.tabberLastPanelID = "{{.LastPanelID}}"
	tools.tabberLastPanelLevels = make(map[string]string)
{{range $level, $id := .LastPanelLevels}}
	tools.tabberLastPanelLevels["{{$level}}"] = "{{$id}}"{{end}}
	cb := tools.notJS.RegisterCallBack(
		func(args []js.Value) {
			target := notJS.GetEventTarget(args[0])
			tools.handleTabButtonOnClick(target)
		},
	)
	for id := range tools.tabberLastPanelLevels {
		tabbar := notJS.GetElementByID(id)
		tools.setTabBarOnClicks(tabbar, cb)
	}
}

func (tools *Tools) setTabBarOnClicks(tabbar js.Value, cb js.Callback) {
	notJS := tools.notJS
	children := notJS.ChildrenSlice(tabbar)
	for _, ch := range children {
		if notJS.TagName(ch) == "BUTTON" {
			ch.Set("onclick", cb)
		}
	}
}

func (tools *Tools) handleTabButtonOnClick(button js.Value) {
	tools.setTabButtonFocus(button)
	nextpanelid := tools.notJS.ID(button) + "Panel"
	if nextpanelid != tools.tabberLastPanelID {
		// clear this level
		parts := strings.Split(nextpanelid, "-")
		nextpanellevel := parts[0]
		tools.IDHide(tools.tabberLastPanelLevels[nextpanellevel])
		// show the next panel
		tools.IDShow(nextpanelid)
		// remember next panel. it is now the last panel.
		tools.tabberLastPanelID = nextpanelid
		tools.tabberLastPanelLevels[nextpanellevel] = nextpanelid
	}
	tools.SizeApp()
}

func (tools *Tools) setTabButtonFocus(tabinfocus js.Value) {
	// focus the tab now in focus
	notJS := tools.notJS
	notJS.ClassListReplaceClass(tabinfocus, UnSelectedTabClassName, SelectedTabClassName)
	p := notJS.ParentNode(tabinfocus)
	children := notJS.ChildrenSlice(p)
	for _, ch := range children {
		if ch != tabinfocus && notJS.TagName(ch) == "BUTTON" && notJS.ClassListContains(ch, SelectedTabClassName) {
			notJS.ClassListReplaceClass(ch, SelectedTabClassName, UnSelectedTabClassName)
		}
	}
}
`
