package main

import (
	"github.com/josephbudd/kickwasm/examples/contacts/domain/interfaces/caller"
	"github.com/josephbudd/kickwasm/examples/contacts/domain/types"
	"github.com/josephbudd/kickwasm/examples/contacts/renderer/interfaces/panelHelper"
	"github.com/josephbudd/kickwasm/examples/contacts/renderer/notjs"
	"github.com/josephbudd/kickwasm/examples/contacts/renderer/panels/AddButton/AddContactPanel"
	"github.com/josephbudd/kickwasm/examples/contacts/renderer/panels/EditButton/EditContactEditPanel"
	"github.com/josephbudd/kickwasm/examples/contacts/renderer/panels/EditButton/EditContactNotReadyPanel"
	"github.com/josephbudd/kickwasm/examples/contacts/renderer/panels/EditButton/EditContactSelectPanel"
	"github.com/josephbudd/kickwasm/examples/contacts/renderer/panels/RemoveButton/RemoveContactConfirmPanel"
	"github.com/josephbudd/kickwasm/examples/contacts/renderer/panels/RemoveButton/RemoveContactNotReadyPanel"
	"github.com/josephbudd/kickwasm/examples/contacts/renderer/panels/RemoveButton/RemoveContactSelectPanel"
	"github.com/josephbudd/kickwasm/examples/contacts/renderer/viewtools"
)

/*

	DO NOT EDIT THIS FILE.

	This file is generated by kickasm and regenerated by rekickasm.

*/

func doPanels(quitCh chan struct{}, tools *viewtools.Tools, callMap map[types.CallID]caller.Renderer, notJS *notjs.NotJS, helper panelHelper.Helper) {
	// 1. Construct the panel code.
	addContactPanel := AddContactPanel.NewPanel(quitCh, tools, notJS, callMap, helper)
	editContactEditPanel := EditContactEditPanel.NewPanel(quitCh, tools, notJS, callMap, helper)
	editContactNotReadyPanel := EditContactNotReadyPanel.NewPanel(quitCh, tools, notJS, callMap, helper)
	editContactSelectPanel := EditContactSelectPanel.NewPanel(quitCh, tools, notJS, callMap, helper)
	removeContactConfirmPanel := RemoveContactConfirmPanel.NewPanel(quitCh, tools, notJS, callMap, helper)
	removeContactNotReadyPanel := RemoveContactNotReadyPanel.NewPanel(quitCh, tools, notJS, callMap, helper)
	removeContactSelectPanel := RemoveContactSelectPanel.NewPanel(quitCh, tools, notJS, callMap, helper)

	// 2. Size the app.
	tools.SizeApp()

	// 3. Start each panel's initial calls.
	addContactPanel.InitialCalls()
	editContactEditPanel.InitialCalls()
	editContactNotReadyPanel.InitialCalls()
	editContactSelectPanel.InitialCalls()
	removeContactConfirmPanel.InitialCalls()
	removeContactNotReadyPanel.InitialCalls()
	removeContactSelectPanel.InitialCalls()
}
