title : Test 1
importPath : github.com/josephbudd/kickwasm/examples/test1
stores :
  - Test1
homes :
  - name : Home1
    button :
      name : Button1Button
      label : Button 1
      heading : Button 1 Heading.
      panelFiles :
        - level2/panel.yaml

