// +build js, wasm

package schoolcoursecopychoosepanel

import (
	"fmt"
	"syscall/js"

	"github.com/josephbudd/kickwasm/proofs/tp2b/tp2btest/rendererprocess/api/markup"
	"github.com/josephbudd/kickwasm/proofs/tp2b/tp2btest/rendererprocess/framework/viewtools"
)

/*

	DO NOT EDIT THIS FILE.

	This file is generated by kickasm and regenerated by rekickasm.

*/

// panelGroup is a group of 4 panels.
// It also has show panel funcs for each panel in this panel group.
type panelGroup struct {
	schoolCourseCopyCompletedPanel js.Value
	schoolCourseCopyChoosePanel js.Value
	schoolCourseCopyPracticePanel js.Value
	schoolCourseCopyTestPanel js.Value
}

func (group *panelGroup) defineMembers() (err error) {

	defer func() {
		if err != nil {
			err = fmt.Errorf("(group *panelGroup) defineMembers(): %w", err)
		}
	}()

    var panel *markup.Element
 if panel = document.ElementByID("mainMasterView_home_pad_SchoolButton_SchoolPanel_tab_bar-SchoolCourseCopyTabPanel-inner-SchoolCourseCopyCompletedPanel"); panel == nil {
	err = fmt.Errorf("unable to find #mainMasterView_home_pad_SchoolButton_SchoolPanel_tab_bar-SchoolCourseCopyTabPanel-inner-SchoolCourseCopyCompletedPanel")
		return
    }
    group.schoolCourseCopyCompletedPanel = panel.JSValue()
 if panel = document.ElementByID("mainMasterView_home_pad_SchoolButton_SchoolPanel_tab_bar-SchoolCourseCopyTabPanel-inner-SchoolCourseCopyChoosePanel"); panel == nil {
	err = fmt.Errorf("unable to find #mainMasterView_home_pad_SchoolButton_SchoolPanel_tab_bar-SchoolCourseCopyTabPanel-inner-SchoolCourseCopyChoosePanel")
		return
    }
    group.schoolCourseCopyChoosePanel = panel.JSValue()
 if panel = document.ElementByID("mainMasterView_home_pad_SchoolButton_SchoolPanel_tab_bar-SchoolCourseCopyTabPanel-inner-SchoolCourseCopyPracticePanel"); panel == nil {
	err = fmt.Errorf("unable to find #mainMasterView_home_pad_SchoolButton_SchoolPanel_tab_bar-SchoolCourseCopyTabPanel-inner-SchoolCourseCopyPracticePanel")
		return
    }
    group.schoolCourseCopyPracticePanel = panel.JSValue()
 if panel = document.ElementByID("mainMasterView_home_pad_SchoolButton_SchoolPanel_tab_bar-SchoolCourseCopyTabPanel-inner-SchoolCourseCopyTestPanel"); panel == nil {
	err = fmt.Errorf("unable to find #mainMasterView_home_pad_SchoolButton_SchoolPanel_tab_bar-SchoolCourseCopyTabPanel-inner-SchoolCourseCopyTestPanel")
		return
    }
    group.schoolCourseCopyTestPanel = panel.JSValue()

	return
}

/*
	Show panel funcs.

	Call these from the controller, presenter and messenger.
*/

// showSchoolCourseCopyCompletedPanel shows the panel you named SchoolCourseCopyCompletedPanel while hiding any other panels in this panel group.
// That panel will become visible only when this group of panels becomes visible.
/* Your note for that panel is:
Displayed when the user has successfully copied for this lesson.
Maybe it should display the results.

*/
func (group *panelGroup) showSchoolCourseCopyCompletedPanel() {
	viewtools.ShowPanelInTabGroup(group.schoolCourseCopyCompletedPanel)
}


// showSchoolCourseCopyChoosePanel shows the panel you named SchoolCourseCopyChoosePanel while hiding any other panels in this panel group.
// This panel will become visible only when this group of panels becomes visible.
/* Your note for this panel is:
Displayed when the user has successfully copied for this lesson.
Maybe it should display the results.

*/
func (group *panelGroup) showSchoolCourseCopyChoosePanel() {
	viewtools.ShowPanelInTabGroup(group.schoolCourseCopyChoosePanel)
}


// showSchoolCourseCopyPracticePanel shows the panel you named SchoolCourseCopyPracticePanel while hiding any other panels in this panel group.
// That panel will become visible only when this group of panels becomes visible.
/* Your note for that panel is:
A page to let the user copy without recording the results.
*/
func (group *panelGroup) showSchoolCourseCopyPracticePanel() {
	viewtools.ShowPanelInTabGroup(group.schoolCourseCopyPracticePanel)
}


// showSchoolCourseCopyTestPanel shows the panel you named SchoolCourseCopyTestPanel while hiding any other panels in this panel group.
// That panel will become visible only when this group of panels becomes visible.
/* Your note for that panel is:
A page to let the user copy with results recorded.
*/
func (group *panelGroup) showSchoolCourseCopyTestPanel() {
	viewtools.ShowPanelInTabGroup(group.schoolCourseCopyTestPanel)
}

