// +build js, wasm

package secondtab

import (
	"context"

	"github.com/josephbudd/kickwasm/examples/spawntabs/rendererprocess/framework/lpc"
	"github.com/josephbudd/kickwasm/examples/spawntabs/rendererprocess/paneling"
	helloworldtemplatepanel "github.com/josephbudd/kickwasm/examples/spawntabs/rendererprocess/spawnPanels/TabsButton/TabsButtonTabBarPanel/SecondTab/HelloWorldTemplatePanel"
)

/*

	DO NOT EDIT THIS FILE.

	This file is generated by kickasm and regenerated by rekickasm.

*/

// Prepare initializes this package in preparation for spawning.
func Prepare(ctx context.Context, ctxCancel context.CancelFunc, receiveChan lpc.Receiving, sendChan lpc.Sending, help *paneling.Help) {
	rendererProcessCtx = ctx

	helloworldtemplatepanel.Prepare(ctxCancel, receiveChan, sendChan, help)
}
