// +build js, wasm

package secondtab

import (
	"github.com/josephbudd/kickwasm/examples/spawntabs/rendererprocess/lpc"
	"github.com/josephbudd/kickwasm/examples/spawntabs/rendererprocess/notjs"
	"github.com/josephbudd/kickwasm/examples/spawntabs/rendererprocess/paneling"
	helloworldtemplatepanel "github.com/josephbudd/kickwasm/examples/spawntabs/rendererprocess/spawnPanels/TabsButton/TabsButtonTabBarPanel/SecondTab/HelloWorldTemplatePanel"
	"github.com/josephbudd/kickwasm/examples/spawntabs/rendererprocess/viewtools"
)

/*

	DO NOT EDIT THIS FILE.

	This file is generated by kickasm and regenerated by rekickasm.

*/

// Prepare initializes this package in preparation for spawning.
func Prepare(quitChan, eojChan chan struct{}, receiveChan lpc.Receiving, sendChan lpc.Sending, vtools *viewtools.Tools, njs *notjs.NotJS, help *paneling.Help) {
	tools = vtools

	helloworldtemplatepanel.Prepare(quitChan, eojChan, receiveChan, sendChan, vtools, njs, help)
}
