package store

import (
	"fmt"
	"strings"

)

/*
	DO NOT EDIT THIS FILE.

	USE THE TOOL kickstore TO ADD OR REMOVE STORES.

	kickstore WILL EDIT THIS FILE FOR YOU.
*/

/*
	Package main's func buildStores() will build a pointer to a type Stores.
	It will eventually end up being passed to your lpc message handlers
	  so that they can use the stores.
*/

// Stores is each of the application's storers.
// You haven't added any stores yet.
// Use kickstore to add or remove local bolt stores and remote service APIs.
type Stores struct {
}

// Open opens every store.
// It returns all of the errors as one single error.
func (stores *Stores) Open() (err error) {

	errList := make([]string, 0, 0)
	defer func() {
		if len(errList) > 0 {
			err = fmt.Errorf(strings.Join(errList, "\n"))
		}
	}()


	return
}

// Close closes every store.
// It returns all of the errors as one single error.
func (stores *Stores) Close() (err error) {

	errList := make([]string, 0, 0)
	defer func() {
		if len(errList) > 0 {
			err = fmt.Errorf(strings.Join(errList, "\n"))
		}
	}()


	return
}
