package templates

// NoStoresGo is the stores.go file when there are no stores.
const NoStoresGo = `{{ $Dot := . }}package main

import (
	"{{.ApplicationGitPath}}{{.ImportDomainStore}}"
)

/*
	DO NOT EDIT THIS FILE.

	USE THE TOOL kickstore TO ADD OR REMOVE STORES.

	kickstore WILL EDIT THIS FILE FOR YOU.
*/

// buildStores makes the bolt data stores.
// However, you haven't added any stores yet.
func buildStores() (stores *store.Stores, err error) {
	stores = &store.Stores{}
	return
}
`

// StoresGo is the stores.go file.
const StoresGo = `{{ $Dot := . }}package main

import (
	"path/filepath"

	"github.com/boltdb/bolt"
	"github.com/pkg/errors"

	"{{.ApplicationGitPath}}{{.ImportDomainDataFilepaths}}"
	"{{.ApplicationGitPath}}{{.ImportDomainStore}}"
	"{{.ApplicationGitPath}}{{.ImportDomainStoreStoring}}"
)

/*
	DO NOT EDIT THIS FILE.

	USE THE TOOL kickstore TO ADD OR REMOVE STORES.

	kickstore will edit this file for you.

*/

// buildStores makes bolt data stores.
// It also opens the bolt database.
// The stores can be close with stores.Close()
func buildStores() (stores *store.Stores, err error) {

	defer func() {
		if err != nil {
			err = errors.WithMessage(err, "buildStores()")
		}
	}()

	var path string
	if path, err = filepaths.BuildUserSubFoldersPath("boltdb"); err != nil {
		err = errors.WithMessage(err, "filepaths.BuildUserSubFoldersPath(\"boltdb\")")
		return
	}
	path = filepath.Join(path, "stores.nosql")
	var db *bolt.DB
	if db, err = bolt.Open(path, filepaths.GetFmode(), nil); err != nil {
		err = errors.WithMessage(err, "bolt.Open(path, filepaths.GetFmode(), nil)")
		return
	}
	stores = &store.Stores{
{{ range .Stores }}		{{.}}: storing.New{{.}}BoltDB(db, path, filepaths.GetFmode()),
{{ end }}	}
	return
}
`
