title : Contacts Manager Example
importPath : github.com/josephbudd/kickwasm/examples/contacts

repos :
  - Contact

services :
  - name : AddAContact
    button :
      label : Add
      name : AddButton
      heading : Add A New Contact.
      panelFiles :
        - services/add/add_panel.yaml
  - name : EditAContact
    button :
      label : Edit
      name : EditButton
      heading : Edit A Contact.
      panelFiles :
        - services/edit/not_ready_panel.yaml
        - services/edit/select_panel.yaml
        - services/edit/edit_panel.yaml
  - name : RemoveAContact
    button :
      label : Remove
      name : RemoveButton
      heading : Remove A Contact.
      panelFiles :
        - services/remove/not_ready_panel.yaml
        - services/remove/select_panel.yaml
        - services/remove/confirm_panel.yaml

