// +build js, wasm

package createpanel

import (
	"fmt"
	"syscall/js"

	"github.com/josephbudd/kickwasm/examples/spawntabs/rendererprocess/api/markup"
	"github.com/josephbudd/kickwasm/examples/spawntabs/rendererprocess/framework/viewtools"
)

/*

	DO NOT EDIT THIS FILE.

	This file is generated by kickasm and regenerated by rekickasm.

*/

// panelGroup is a group of 1 panel.
// It also has a show panel func for each panel in this panel group.
type panelGroup struct {
	createPanel js.Value
}

func (group *panelGroup) defineMembers() (err error) {

	defer func() {
		if err != nil {
			err = fmt.Errorf("(group *panelGroup) defineMembers(): %w", err)
		}
	}()

    var panel *markup.Element
 if panel = document.ElementByID("mainMasterView_home_pad_TabsButton_TabsButtonTabBarPanel_tab_bar-FirstTabPanel-inner-CreatePanel"); panel == nil {
	err = fmt.Errorf("unable to find #mainMasterView_home_pad_TabsButton_TabsButtonTabBarPanel_tab_bar-FirstTabPanel-inner-CreatePanel")
		return
    }
    group.createPanel = panel.JSValue()

	return
}

/*
	Show panel funcs.

	Call these from the controller, presenter and messenger.
*/

// showCreatePanel shows the panel you named CreatePanel while hiding any other panels in this panel group.
// This panel will become visible only when this group of panels becomes visible.
/* Your note for this panel is:
Button to create a new hello world.
*/
func (group *panelGroup) showCreatePanel() {
	viewtools.ShowPanelInTabGroup(group.createPanel)
}

