package service4level5markuppanel

import (
	"syscall/js"

	"github.com/pkg/errors"
)

/*

	DO NOT EDIT THIS FILE.

	This file is generated by kickasm and regenerated by rekickasm.

*/

// panelGroup is a group of 1 panel.
// It also has a show panel func for each panel in this panel group.
type panelGroup struct {
	service4Level5MarkupPanel js.Value
}

func (group *panelGroup) defineMembers() (err error) {

	defer func() {
		if err != nil {
			err = errors.WithMessage(err, "(group *panelGroup) defineMembers()")
		}
	}()

	if group.service4Level5MarkupPanel = notJS.GetElementByID("tabsMasterView-home-pad-Service4Button-Service4Level1ButtonPanel-Service4ToLevel2ColorsButton-Service4Level2ButtonPanel-Service4ToLevel3ColorsButton-Service4Level3ButtonPanel-Service4ToLevel4ColorsButton-Service4Level4ButtonPanel-Service4ToLevel5ColorsButton-Service4Level5ButtonPanel-Service4Level5ContentButton-Service4Level5MarkupPanel"); group.service4Level5MarkupPanel == null {
		err = errors.New("unable to find #tabsMasterView-home-pad-Service4Button-Service4Level1ButtonPanel-Service4ToLevel2ColorsButton-Service4Level2ButtonPanel-Service4ToLevel3ColorsButton-Service4Level3ButtonPanel-Service4ToLevel4ColorsButton-Service4Level4ButtonPanel-Service4ToLevel5ColorsButton-Service4Level5ButtonPanel-Service4Level5ContentButton-Service4Level5MarkupPanel")
		return
	}

	return
}

/*
	Show panel funcs.

	Call these from the controller, presenter and caller.
*/

// showService4Level5MarkupPanel shows the panel you named Service4Level5MarkupPanel while hiding any other panels in this panel group.
// This panel's id is tabsMasterView-home-pad-Service4Button-Service4Level1ButtonPanel-Service4ToLevel2ColorsButton-Service4Level2ButtonPanel-Service4ToLevel3ColorsButton-Service4Level3ButtonPanel-Service4ToLevel4ColorsButton-Service4Level4ButtonPanel-Service4ToLevel5ColorsButton-Service4Level5ButtonPanel-Service4Level5ContentButton-Service4Level5MarkupPanel.
// This panel either becomes visible immediately or whenever this group of panels is made visible.  Whenever could be immediately if this panel group is currently visible.
// Param force boolean effects when this panel becomes visible.
//  * if force is true then
//    immediately if the home button pad is not currently displayed;
//    whenever if the home button pad is currently displayed.
//  * if force is false then whenever.
/* Your note for this panel is:
This is the only content.
Brought to you in the first service color.

*/
func (group *panelGroup) showService4Level5MarkupPanel(force bool) {
	tools.ShowPanelInButtonGroup(group.service4Level5MarkupPanel, force)
}
