package main

import (
	"github.com/josephbudd/kickwasm/examples/spawntabs/renderer/lpc"
	"github.com/josephbudd/kickwasm/examples/spawntabs/renderer/notjs"
	"github.com/josephbudd/kickwasm/examples/spawntabs/renderer/paneling"
	"github.com/josephbudd/kickwasm/examples/spawntabs/renderer/panels/TabsButton/TabsButtonTabBarPanel/FirstTab/CreatePanel"
	"github.com/josephbudd/kickwasm/examples/spawntabs/renderer/spawnPanels/TabsButton/TabsButtonTabBarPanel"
	"github.com/josephbudd/kickwasm/examples/spawntabs/renderer/viewtools"
)

/*

	DO NOT EDIT THIS FILE.

	This file is generated by kickasm and regenerated by rekickasm.

*/

func doPanels(client *lpc.Client, quitChan, eojChan chan struct{}, receiveChan lpc.Receiving, sendChan lpc.Sending,
	tools *viewtools.Tools, notJS *notjs.NotJS, help *paneling.Help) (err error) {

	// 1. Prepare the spawn panels.
	tabsbuttontabbarpanel.Prepare(client, quitChan, eojChan, receiveChan, sendChan, tools, notJS, help)

	// 2. Construct the panel code.
	var createPanel *createpanel.Panel
	if createPanel, err = createpanel.NewPanel(quitChan, eojChan, receiveChan, sendChan, tools, notJS, help); err != nil {
		tools.ConsoleLog("doPanels: erorr is " + err.Error())
		return
	}

	// No errors so continue.
	tools.ConsoleLog("doPanels: no erorrs")

	// 3. Size the app.
	tools.SizeApp()

	// 4. Start each panel's listening for the main process.
	createPanel.Listen()

	// 5. Start each panel's initial calls.
	createPanel.InitialCalls()

	return
}
