package service3level4markuppanel

import (
	"syscall/js"

	"github.com/pkg/errors"
)

/*

	DO NOT EDIT THIS FILE.

	This file is generated by kickasm and regenerated by rekickasm.

*/

// panelGroup is a group of 1 panel.
// It also has a show panel func for each panel in this panel group.
type panelGroup struct {
	service3Level4MarkupPanel js.Value
}

func (group *panelGroup) defineMembers() (err error) {

	defer func() {
		if err != nil {
			err = errors.WithMessage(err, "(group *panelGroup) defineMembers()")
		}
	}()

	if group.service3Level4MarkupPanel = notJS.GetElementByID("tabsMasterView-home-pad-Service3Button-Service3Level1ButtonPanel-Service3ToLevel2ColorsButton-Service3Level2ButtonPanel-Service3ToLevel3ColorsButton-Service3Level3ButtonPanel-Service3ToLevel4ColorsButton-Service3Level4ButtonPanel-Service3Level4ContentButton-Service3Level4MarkupPanel"); group.service3Level4MarkupPanel == null {
		err = errors.New("unable to find #tabsMasterView-home-pad-Service3Button-Service3Level1ButtonPanel-Service3ToLevel2ColorsButton-Service3Level2ButtonPanel-Service3ToLevel3ColorsButton-Service3Level3ButtonPanel-Service3ToLevel4ColorsButton-Service3Level4ButtonPanel-Service3Level4ContentButton-Service3Level4MarkupPanel")
		return
	}

	return
}

/*
	Show panel funcs.

	Call these from the controller, presenter and caller.
*/

// showService3Level4MarkupPanel shows the panel you named Service3Level4MarkupPanel while hiding any other panels in this panel group.
// This panel's id is tabsMasterView-home-pad-Service3Button-Service3Level1ButtonPanel-Service3ToLevel2ColorsButton-Service3Level2ButtonPanel-Service3ToLevel3ColorsButton-Service3Level3ButtonPanel-Service3ToLevel4ColorsButton-Service3Level4ButtonPanel-Service3Level4ContentButton-Service3Level4MarkupPanel.
// This panel either becomes visible immediately or whenever this group of panels is made visible.  Whenever could be immediately if this panel group is currently visible.
// Param force boolean effects when this panel becomes visible.
//  * if force is true then
//    immediately if the home button pad is not currently displayed;
//    whenever if the home button pad is currently displayed.
//  * if force is false then whenever.
/* Your note for this panel is:
This is the only content.
Brought to you in the first service color.

*/
func (group *panelGroup) showService3Level4MarkupPanel(force bool) {
	tools.ShowPanelInButtonGroup(group.service3Level4MarkupPanel, force)
}
