package main

import (
	"fmt"
	"log"
	"net"

	"github.com/josephbudd/kickwasm/examples/colors/domain/data/settings"
	"github.com/josephbudd/kickwasm/examples/colors/domain/store"
	"github.com/josephbudd/kickwasm/examples/colors/domain/types"
	"github.com/josephbudd/kickwasm/examples/colors/mainprocess/lpc"
	"github.com/josephbudd/kickwasm/examples/colors/mainprocess/lpc/dispatch"
)

/*
	DO NOT EDIT THIS FILE.

	kicklpc and kickstore will alter this file.

*/

/*

	Data Storage:
	 * /domain/store/storer is the storer interfaces.
	 * /domain/store/storing is the bolt implementations of the storer interfaces.
	 * /domain/store/record is the record definitions.

*/

func main() {
	var err error
	// build the stores and setup the close.
	var stores *store.Stores
	if stores, err = buildStores(); err != nil {
		log.Println(err)
		return
	}
	// close the bolt store later.
	defer stores.Close()

	// get the application's host and port and then setup the listener.
	var appSettings *types.ApplicationSettings
	if appSettings, err = settings.NewApplicationSettings(); err != nil {
		log.Println(err)
		return
	}

	// initialize and start the listener.
	// the listener may have reset the address if "localhost:0".
	// use the listener's address.
	location := fmt.Sprintf("%s:%d", appSettings.Host, appSettings.Port)
	var listener net.Listener
	if listener, err = net.Listen("tcp", location); err != nil {
		log.Println(err)
		return
	}
	// get the channels
	sendChan, receiveChan, eojChan := lpc.Channels()
	quitChan := make(chan struct{}, 1)
	// process incoming lpcs.
	go func() {

		defer func() {
			log.Println("eoj for processing incoming lpcs.")
		}()

		// wait for the server to end and then stop lpc go funcs
		log.Println("listening for receiveChan")
		for {
			select {
			case cargo := <-receiveChan:
				log.Println("main: got cargo := <-receiveChan")
				dispatch.Do(cargo, sendChan, eojChan, stores)
			case <-quitChan:
				log.Println("main: got <-quitChan")
				eojChan.Signal()
				return
			}
		}
	}()
	// make the call server.
	server := lpc.NewServer(listener, quitChan, receiveChan, sendChan)
	server.Run(serve)
}
