// +build js, wasm

package helloworldtemplatepanel

import (
	"fmt"

	"github.com/josephbudd/kickwasm/examples/spawnwidgets/rendererprocess/framework/lpc"
	"github.com/josephbudd/kickwasm/examples/spawnwidgets/rendererprocess/api/markup"
	"github.com/josephbudd/kickwasm/examples/spawnwidgets/rendererprocess/paneling"
)

/*

	Panel name: HelloWorldTemplatePanel

*/

/*

	DO NOT EDIT THIS FILE.

*/

// Prepare prepares the panel to be spawned.
// This is called once by package main when the application starts.
func Prepare(quitChan, eojChan chan struct{}, receiveChan lpc.Receiving, sendChan lpc.Sending, phelp *paneling.Help) {
	quitCh = quitChan
	eojCh = eojChan
	receiveCh = receiveChan
	sendCh = sendChan
	help = phelp
}

// BuildPanel builds the panel's go code.
// Returns the error.
func BuildPanel(uniqueID uint64, tabButton, tabPanelHeader *markup.Element, panelNameID map[string]string, panelData interface{}, unspawn func() error) (prepareToUnSpawn func(), err error) {

	defer func() {
		if err != nil {
			err = fmt.Errorf("%s.BuildPanel(): %w", "helloworldtemplatepanel", err)
		}
	}()

	// make the panel
	panel := newPanel(uniqueID, tabButton, tabPanelHeader, panelNameID, panelData, unspawn)
	prepareToUnSpawn = panel.PrepareToUnSpawn

	if err = panel.group.defineMembers(); err != nil {
		return
	}
	if err = panel.controller.defineControlsHandlers(); err != nil {
		return
	}
	if err = panel.presenter.defineMembers(); err != nil {
		return
	}
	panel.messenger.dispatchMessages()
	panel.controller.initialCalls()
	panel.messenger.initialSends()

	return
}

// PrepareToUnSpawn prepares to unspawn.
func (panel *spawnedPanel) PrepareToUnSpawn() {
	panel.messenger.unSpawningCh <- struct{}{}
	panel.controller.UnSpawning()
}
