package about

import "fmt"

const (
	major  uint = 1
	minor  uint = 0
	bugfix uint = 0
)

// String stringifys version.
func String() string {
	return fmt.Sprintf("%d.%d.%d", major, minor, bugfix)
}

// GetReleases returns the history of changes to this application.
// Be careful editing this.
// Make sure you understand this data structure.
func GetReleases() map[string]map[string][]string {
	return map[string]map[string][]string{
		"0.0.0": map[string][]string{
			"Once Upon A Time...": []string{
				`kick was born from a computer program user interface I would write for programs I created. kick happend because I got tired of writting the same type of user interface over and over again.`,
			},
			"Now...": []string{
				`kick has been refactored into kickwasm. A desktop program framework written entirely in go.`,
				`Honestly, It is so much easier to write a renderer in golang than in javascript.`,
			},
		},
		"1.0.0": map[string][]string{
			"This application was generated by the new kickwasm.": []string{
				`It should also give you an idea of how kickwasm generated source code is laid out.`,
			},
		},
	}
}

// GetContributors returns those who contributed to this application in any way.
// This is where the names of each man or woman involve in this application should be listed.
// Each entry is a name and a saying or comment.
func GetContributors() map[string]string {
	return map[string]string{
		"Joe Budd": "I write code.",
	}
}

// Credit is information about things and people you need to acknowledge.
type Credit struct {
	Name        string
	Description string
	URL         string
}

// GetCredits returns the credits.
// Do not remove the kick or lpc references.
// Only remove the bolt reference if you remove bolt from this application.
// Be verbose! Show how appreciatative and good natured you are.
// Mention any software, speakers and writers that helped you build this application in any way.
// Don't forget people and things that helped you in more remote ways as well.
func GetCredits() []Credit {
	return []Credit{
		Credit{
			Name:        "kickwasm",
			Description: "A way to kick start your golang application.",
			URL:         "https://www.github.com/josephbudd/kickwasm",
		},
		Credit{
			Name:        "bolt",
			Description: "the bolt database.",
			URL:         "https://www.github.com/boltdb/bolt",
		},
	}
}

// License is software license information.
type License struct {
	Software string
	License  string
	Location string
}

// GetLicenses returns the licenses.
// Add your license info to this list.
// Add license info for other software that you use in this application.
func GetLicenses() []License {
	return []License{
		License{
			Software: "Some of the code in this application was liberally copied from go source files which are distributed under the following license.",
			License: `Copyright (c) 2009 The Go Authors. All rights reserved.
			
			Redistribution and use in source and binary forms, with or without
			modification, are permitted provided that the following conditions are
			met:
			
			   * Redistributions of source code must retain the above copyright
			notice, this list of conditions and the following disclaimer.
			   * Redistributions in binary form must reproduce the above
			copyright notice, this list of conditions and the following disclaimer
			in the documentation and/or other materials provided with the
			distribution.
			   * Neither the name of Google Inc. nor the names of its
			contributors may be used to endorse or promote products derived from
			this software without specific prior written permission.
			
			THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
			"AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
			LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
			A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
			OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
			SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
			LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
			DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
			THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
			(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
			OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.`,
			Location: "https://www.golang.org/",
		},
		License{
			Software: "bolt",
			License: `The MIT License (MIT)
			
			Copyright (c) 2013 Ben Johnson
			
			Permission is hereby granted, free of charge, to any person obtaining a copy of
			this software and associated documentation files (the "Software"), to deal in
			the Software without restriction, including without limitation the rights to
			use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
			the Software, and to permit persons to whom the Software is furnished to do so,
			subject to the following conditions:
			
			The above copyright notice and this permission notice shall be included in all
			copies or substantial portions of the Software.
			
			THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
			IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
			FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
			COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
			IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
			CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.`,
			Location: "https://www.github.com/boltdb/bolt",
		},
		License{
			Software: "lpc",
			License: `MIT License
			
			Copyright (c) 2017 Joseph Budd
			
			Permission is hereby granted, free of charge, to any person obtaining a copy
			of this software and associated documentation files (the "Software"), to deal
			in the Software without restriction, including without limitation the rights
			to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
			copies of the Software, and to permit persons to whom the Software is
			furnished to do so, subject to the following conditions:
			
			The above copyright notice and this permission notice shall be included in all
			copies or substantial portions of the Software.
			
			THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
			IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
			FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
			AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
			LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
			OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
			SOFTWARE.`,
			Location: "https://www.github.com/josephbudd/lpc",
		},
		License{
			Software: "kick",
			License: `The MIT License (MIT)
			
			Copyright (c) 2017 Joseph Budd
			
			Permission is hereby granted, free of charge, to any person obtaining a copy of
			this software and associated documentation files (the "Software"), to deal in
			the Software without restriction, including without limitation the rights to
			use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
			the Software, and to permit persons to whom the Software is furnished to do so,
			subject to the following conditions:
			
			The above copyright notice and this permission notice shall be included in all
			copies or substantial portions of the Software.
			
			THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
			IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
			FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
			COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
			IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
			CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
			`,
			Location: "https://www.github.com/josephbudd/kick",
		},
	}
}
