// +build js, wasm

package action3level1markuppanel

import (
	"syscall/js"

	"github.com/pkg/errors"

	"github.com/josephbudd/kickwasm/examples/colors/rendererprocess/markup"
	"github.com/josephbudd/kickwasm/examples/colors/rendererprocess/framework/viewtools"
)

/*

	DO NOT EDIT THIS FILE.

	This file is generated by kickasm and regenerated by rekickasm.

*/

// panelGroup is a group of 1 panel.
// It also has a show panel func for each panel in this panel group.
type panelGroup struct {
	action3Level1MarkupPanel js.Value
}

func (group *panelGroup) defineMembers() (err error) {

	defer func() {
		if err != nil {
			err = errors.WithMessage(err, "(group *panelGroup) defineMembers()")
		}
	}()

    var panel *markup.Element
 if panel = document.ElementByID("mainMasterView-home-pad-Action3Button-Action3Level1ButtonPanel-Action3Level1ContentButton-Action3Level1MarkupPanel"); panel == nil {
		err = errors.New("unable to find #mainMasterView-home-pad-Action3Button-Action3Level1ButtonPanel-Action3Level1ContentButton-Action3Level1MarkupPanel")
		return
    }
    group.action3Level1MarkupPanel = panel.JSValue()

	return
}

/*
	Show panel funcs.

	Call these from the controller, presenter and messenger.
*/

// showAction3Level1MarkupPanel shows the panel you named Action3Level1MarkupPanel while hiding any other panels in this panel group.
// This panel's id is mainMasterView-home-pad-Action3Button-Action3Level1ButtonPanel-Action3Level1ContentButton-Action3Level1MarkupPanel.
// This panel either becomes visible immediately or whenever this group of panels is made visible.  Whenever could be immediately if this panel group is currently visible.
// Param force boolean effects when this panel becomes visible.
//  * if force is true then
//    immediately if the home button pad is not currently displayed;
//    whenever if the home button pad is currently displayed.
//  * if force is false then whenever.
/* Your note for this panel is:
This is the only content.
Brought to you in the first service color.

*/
func (group *panelGroup) showAction3Level1MarkupPanel(force bool) {
	viewtools.ShowPanelInButtonGroup(group.action3Level1MarkupPanel, force)
}
