package service5level3markuppanel

import (
	"syscall/js"

	"github.com/pkg/errors"
)

/*

	DO NOT EDIT THIS FILE.

	This file is generated by kickasm and regenerated by rekickasm.

*/

// panelGroup is a group of 1 panel.
// It also has a show panel func for each panel in this panel group.
type panelGroup struct {

	service5Level3MarkupPanel js.Value
}

func (group *panelGroup) defineMembers() (err error) {

	defer func() {
		if err != nil {
			err = errors.WithMessage(err, "(group *panelGroup) defineMembers()")
		}
	}()

	if group.service5Level3MarkupPanel = notJS.GetElementByID("tabsMasterView-home-pad-Service5Button-Service5Level1ButtonPanel-Service5ToLevel2ColorsButton-Service5Level2ButtonPanel-Service5ToLevel3ColorsButton-Service5Level3ButtonPanel-Service5Level3ContentButton-Service5Level3MarkupPanel"); group.service5Level3MarkupPanel == null {
		err = errors.New("unable to find #tabsMasterView-home-pad-Service5Button-Service5Level1ButtonPanel-Service5ToLevel2ColorsButton-Service5Level2ButtonPanel-Service5ToLevel3ColorsButton-Service5Level3ButtonPanel-Service5Level3ContentButton-Service5Level3MarkupPanel")
		return
	}

	return
}

/*
	Show panel funcs.

	Call these from the controler, presenter and caller.
*/

// showService5Level3MarkupPanel shows the panel you named Service5Level3MarkupPanel while hiding any other panels in this panel group.
// This panel's id is tabsMasterView-home-pad-Service5Button-Service5Level1ButtonPanel-Service5ToLevel2ColorsButton-Service5Level2ButtonPanel-Service5ToLevel3ColorsButton-Service5Level3ButtonPanel-Service5Level3ContentButton-Service5Level3MarkupPanel.
// This panel either becomes visible immediately or whenever this group of panels is made visible.  Whenever could be immediately if this panel group is currently visible.
// Param force boolean effects when this panel becomes visible.
//  * if force is true then
//    immediately if the home button pad is not currently displayed;
//    whenever if the home button pad is currently displayed.
//  * if force is false then whenever.
/* Your note for this panel is:
This is the only content.
Brought to you in the first service color.

*/
func (group *panelGroup) showService5Level3MarkupPanel(force bool) {
	tools.ShowPanelInButtonGroup(group.service5Level3MarkupPanel, force)
}
