package templates

// MainDoPanelsGo is ./panels.go.
const MainDoPanelsGo = `{{$Dot := .}}package main

import ({{range .Imports}}
	"{{.}}"{{end}}
)

/*

	DO NOT EDIT THIS FILE.

	This file is generated by kickasm and regenerated by rekickasm.

*/

func doPanels(quitCh chan struct{}, tools *viewtools.Tools, callMap types.RendererCallMap, notjs *kicknotjs.NotJS) {
	// 1. Construct the panel code.{{range $name, $path := .PanelNamePathMap}}
	{{call $Dot.LowerCamelCase $name}} := {{$name}}.NewPanel(quitCh, tools, notjs, callMap){{end}}{{if .AddAbout}}
	aboutPanel := AboutPanel.NewPanel(quitCh, tools, notjs, callMap){{end}}

	// 2. Size the app.
	tools.SizeApp()

	// 3. Start each panel's initial calls.{{range $name, $path := .PanelNamePathMap}}
	{{call $Dot.LowerCamelCase $name}}.InitialCalls(){{end}}{{if .AddAbout}}
	aboutPanel.InitialCalls(){{end}}
}
`
